version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "06:00"
      timezone: Asia/Riyadh
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns: ["*"]
